name: Qodana CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [AAAmain]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      # for Qodana
      pull-requests: write
      checks: write
      # for GitHub code scanning
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: JetBrains/qodana-action@v2023.3
        # env:
        #   QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # Qodana Cloud と連携する場合
        with:
          post-pr-comment: false
          use-annotations: false
          pr-mode: false
          additional-cache-key: qodana-2023.3-
      - run: |
          cat '${{ runner.temp }}/qodana/results/qodana.sarif.json' \
            | jq 'del(.runs[].automationDetails)' \
            > '${{ runner.temp }}/qodana.sarif'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana.sarif
          category: qodana:jvm-android
