name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - run: ./gradlew androidApp:lintDebug
        continue-on-error: true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./androidApp/build/reports/lint-results-debug.sarif
          category: android-lint:debug
      - run: ./gradlew ktlintCheck --continue
        continue-on-error: true
      - run: |
          cat './androidApp/build/reports/ktlint-results.sarif' \
            | jq '.runs[].results[].locations[].physicalLocation.artifactLocation.uri |= ltrimstr("work/android-sarif-ci-sample/android-sarif-ci-sample/")' \
            > '${{ runner.temp }}/ktlint-results.sarif'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/ktlint-results.sarif
          category: ktlint:androidApp
      - run: |
          cat './shared/build/reports/ktlint-results.sarif' \
            | jq '.runs[].results[].locations[].physicalLocation.artifactLocation.uri |= ltrimstr("work/android-sarif-ci-sample/android-sarif-ci-sample/")' \
            > '${{ runner.temp }}/ktlint-results.sarif'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/ktlint-results.sarif
          category: ktlint:shared
      - uses: MobSF/mobsfscan@main
        with:
          args: . --sarif --output results.sarif
        continue-on-error: true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: mobsfscan

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./androidApp/build/reports

      - uses: actions/deploy-pages@v4
        id: deploy

      - run: |
          echo '${{steps.deploy.outputs.page_url}}'
